# Site settings
title: Spencer Owen
description: The art of progress is to preserve order amid change and preserve change amid order - Alfred North Whitehead
url: 'http://spuder.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: Spencer Owen
  email: owenspencer@gmail.com
  twitter_username: spencer450
  # facebook_username: joshgerdes
  github_username:  spuder
  linkedin_username:  spuder
  stackexchange: http://stackexchange.com/users/1785040/spuder


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
